### PR TITLE
run black

### PR DESCRIPTION
**Pull request by gurneyalex**
so that Travis pre-commit checks pass on the OCA PR.

### CODE REVIEW

**Review by rvalyi — DISMISSED** [review]

**Comment by alexis-via** [comment]
Seems I completely forgot this pre-commit stuff, sorry ! Thanks Alexandre for your PR

**Comment by alexis-via** [comment]
The method _set_iline_product_name() that you added is badly called. I thought you only ran black... but I understand that you also made some manual changes. If I knew it before merging, I would have reviewed it more carefully.

**Comment by gurneyalex** [comment]
@alexis-via  I apologize... I first created the PR without this, and then saw the issue about complexity and forgot to update the description when I squashed. I'll fix the call.

**Comment by gurneyalex** [comment]
@alexis-via https://github.com/akretion/edi/pull/3

**Pull request merged**
